#!/bin/bash

function normal_install() {
    echo -e "\n\033[1;36m Starting Normal Install...\033[0m\n"
    curl -LO https://raw.githubusercontent.com/z399/arch-acetate/master/basebuild > basebuild 
    chmod +x basebuild && ./basebuild
}

function encrypted_install() {
    echo -e "\n\033[1;35m Starting Encrypted Install...\033[0m\n"
    curl -LO https://raw.githubusercontent.com/z399/archcrypt/main/basecrypt > basecrypt 
    chmod +x basecrypt && ./basecrypt
}

clear
echo -e "\n\033[1;33m*******************************************************\033[0m"
echo -e "\033[1;33m*               Welcome to the Arch Linux Installer   *\033[0m"
echo -e "\033[1;33m*******************************************************\033[0m"
cat << "EOF"

 .              +   .                .   . .     .  .
                   .                    .       .     *
  .       *                        . . . .  .   .  + .
            "You Are Here"            .   .  +  . . .
.                 |             .  .   .    .    . .
                  |           .     .     . +.    +  .
                 \|/            .       .   . .
        . .       V          .    * . . .  .  +   .
           +      .           .   .      +
                            .       . +  .+. .
  .                      .     . + .  . .     .      .
           .      .    .     . .   . . .        ! /
      *             .    . .  +    .  .       - O -
          .     .    .  +   . .  *  .       . / |
               . + .  .  .  .. +  .
.      .  .  .  *   .  *  . +..  .            *
 .      .   . .   .   .   . .  +   .    .            +

                               __           _           
   _________  ____ _________  / /__  ____ _(_)___  ____ 
  / ___/ __ \/ __ `/ ___/ _ \/ / _ \/ __ `/ / __ \/ __ \
 (__  ) /_/ / /_/ / /__/  __/ /  __/ /_/ / / /_/ / / / /
/____/ .___/\__,_/\___/\___/_/\___/\__, /_/\____/_/ /_/ 
    /_/                           /____/                                   

EOF
echo -e "\nCreated by: \033[1;32mz399,\033[0m for \033[1;36mSPACELEGION\033[0m"
echo -e "Last Updated: \033[1;34mFebruary 2, 2024\033[0m"


echo -e "\nChoose installation type:"
echo "1. Normal Install"
echo "2. Encrypted Install"
read -p "Enter your choice (1 or 2): " choice


case $choice in
    1)
        normal_install
        ;;
    2)
        encrypted_install
        ;;
    *)
        echo -e "\n\033[1;31mInvalid choice. Please enter \033[1;32m1\033[0m or \033[1;33m2\033[0m.\033[0m\n"
        ;;
esac












